# Generated by Django 6.0.2 on 2026-04-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='telegram_code',
        ),
    ]
