# Generated by Django 6.0.2 on 2026-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_movie_telegram_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='telegram_link',
            field=models.URLField(blank=True, help_text="Telegram post linki (ixtiyoriy, agar mavjud bo'lsa saytda ko'rinadi)", null=True),
        ),
    ]
