# Generated by Django 6.0.2 on 2026-04-10 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_movie_home_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False, help_text="Faqat premium obunachilar ko'ra oladi"),
        ),
        migrations.AlterField(
            model_name='movieepisode',
            name='video_url',
            field=models.URLField(blank=True, help_text='Bunny.net iframe yoki mp4 linkini yozing', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='my_app.profileavatar'),
        ),
        migrations.CreateModel(
            name='SubscriptionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('1_month', '1 Oylik'), ('1_year', '1 Yillik')], max_length=20)),
                ('image', models.ImageField(upload_to='receipts/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
