# Generated by Django 6.0.2 on 2026-04-10 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_profileavatar_movie_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.CharField(blank=True, help_text='Chiqarilgan yili, masalan: 2026', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text="Umumiy ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='subscriptionreceipt',
            name='image',
            field=models.ImageField(upload_to='receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='subscriptionreceipt',
            name='plan',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='FavoriteAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='my_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='my_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
