# Generated by Django 6.0.2 on 2026-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_movie_release_year_movie_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='tier',
            field=models.CharField(choices=[('basic', 'Asosiy (Free)'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=10),
        ),
    ]
