# Generated by Django 6.0.2 on 2026-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_vipuser_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='minimum_tier',
            field=models.CharField(choices=[('basic', 'Asosiy (Free)'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', help_text="Qaysi tarifdan boshlab ko'rish mumkin", max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False, help_text="Faqat premium obunachilar ko'ra oladi (Eski tizim)"),
        ),
    ]
