# Generated by Django 4.2.11 on 2026-09-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_movie_hero_media_moviecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news/')),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Anime nomi', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Kichik sarlavha', max_length=200, null=True)),
                ('image_url', models.URLField(help_text='Poster rasmi URL (masalan: https://i.pinimg.com/...)')),
                ('day', models.CharField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], help_text='Chiqish kuni', max_length=20)),
                ('episode_number', models.PositiveIntegerField(default=1, help_text='Chiqadigan qism raqami')),
                ('fandub', models.CharField(default='AniBest', help_text='Fandub nomi', max_length=100)),
                ('watch_url', models.URLField(help_text="Ko'rish havolasi (masalan: https://bestmedia-official.uz/movie/7/)")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kichik raqam avval chiqadi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JackpotCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reward_type', models.CharField(choices=[('vip_hour', 'VIP obuna (soatlik)'), ('vip_day', 'VIP obuna (kunlik)'), ('balance', 'Hisobga pul')], default='balance', max_length=10)),
                ('vip_hours', models.PositiveIntegerField(blank=True, default=0, help_text="reward_type=vip_hour bo'lsa nechta soat")),
                ('vip_days', models.PositiveIntegerField(blank=True, default=0, help_text="reward_type=vip_day bo'lsa nechta kun")),
                ('balance_amount', models.PositiveIntegerField(blank=True, default=0, help_text="reward_type=balance bo'lsa nechta so'm")),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Nechta foydalanuvchi ishlata oladi (0 = cheksiz)')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Bo'sh qoldirilsa — muddatsiz amal qiladi (admin o'zi bekor qilmaguncha)", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jackpot kod',
                'verbose_name_plural': 'Jackpot kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoResultsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', help_text='Rasmmi yoki videomi?', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Yashil (chroma-key) fonli rasm — fon avtomatik shaffof qilinadi', null=True, upload_to='no_results/')),
                ('video', models.FileField(blank=True, help_text='Yashil (chroma-key) fonli video — fon avtomatik shaffof qilinadi', null=True, upload_to='no_results/videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qidiruv - Natija topilmadi (media)',
                'verbose_name_plural': 'Qidiruv - Natija topilmadi (media)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='premium_backgrounds/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premium fon',
                'verbose_name_plural': 'Premium fonlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Musiqa nomi (foydalanuvchiga shu nom ko'rinadi)", max_length=200)),
                ('file', models.FileField(help_text='Musiqa fayli (mp3)', upload_to='premium_music/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kichik raqam avval chiqadi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premium musiqa',
                'verbose_name_plural': 'Premium musiqalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='reelbest/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reelbest/thumbnails/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ReelBest',
                'verbose_name_plural': "ReelBest'lar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('video', models.FileField(blank=True, null=True, upload_to='stories/videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='activesession',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activesession',
            name='device_name',
            field=models.CharField(blank=True, help_text='Browser + OS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activesession',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobil'), ('tablet', 'Planshet'), ('desktop', 'Kompyuter'), ('unknown', "Noma'lum")], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='activesession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activesession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activesession',
            name='location',
            field=models.CharField(blank=True, help_text='Taxminiy joylashuv', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activesession',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activesession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='about_info',
            field=models.TextField(blank=True, help_text="'Anime haqida' bo'limida chiqadigan matn (admin kiritadi)", null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='intro_time',
            field=models.CharField(blank=True, help_text="Intro oralig'i (faqat qismsiz film uchun), masalan: 2:55 | 3:17", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Anime reytingi, masalan: 8.5', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Agar bu boshqa izohga javob bo'lsa, o'sha izoh shu yerda", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='my_app.moviecomment'),
        ),
        migrations.AddField(
            model_name='movieepisode',
            name='intro_time',
            field=models.CharField(blank=True, help_text="Intro oralig'i, masalan: 2:55 | 3:17", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='last_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='my_app.movieepisode'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_music_on', models.BooleanField(default=False)),
                ('premium_music_volume', models.PositiveSmallIntegerField(default=50, help_text="0-100 oralig'ida ovoz balandligi")),
                ('beta_home_on', models.BooleanField(default=False, help_text="Yoqilsa, bosh sahifa o'rniga home_vip.html ko'rsatiladi")),
                ('beta_home_expire', models.DateTimeField(blank=True, help_text="Sinov muddati tugash vaqti — o'tgach avtomatik o'chadi", null=True)),
                ('theme', models.CharField(choices=[('dark', "Qorong'i"), ('white', 'Oq'), ('rose', "Qizil / Ro'za"), ('premium', "Premium (To'q binafsha)")], default='dark', max_length=20)),
                ('bg_color', models.CharField(default='#0a0a0f', help_text="Hex yoki gradient kalit so'z", max_length=30)),
                ('bg_color_custom', models.CharField(blank=True, default='#0a0a0f', max_length=30, null=True)),
                ('tabbar_on', models.BooleanField(default=True)),
                ('premium_bg_on', models.BooleanField(default=False)),
                ('telegram_download_on', models.BooleanField(default=False)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_notify_on', models.BooleanField(default=False, help_text="Yangi epizod yoki xabar bo'lganda Telegram orqali xabar yuborish")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premium_bg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='my_app.premiumbackground')),
                ('premium_music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='my_app.premiummusic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, help_text="Hisobdagi mablag' / ball")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReelBestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='my_app.reelbest')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='my_app.reelbestcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reelbest_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='reelbest',
            name='movie',
            field=models.ForeignKey(blank=True, help_text="Ixtiyoriy — tanlansa 'Animeni ko'rish' tugmasi chiqadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reelbest_items', to='my_app.movie'),
        ),
        migrations.AddField(
            model_name='reelbest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reelbest_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push obuna',
                'verbose_name_plural': 'Push obunalar',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('admin', 'Admin xabari'), ('reply', 'Chatda javob')], default='admin', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Yuborgan admin yoki javob yozgan foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notices', to=settings.AUTH_USER_MODEL)),
                ('related_chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='my_app.chatmessage')),
                ('related_movie_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='my_app.moviecomment')),
                ('target_user', models.ForeignKey(blank=True, help_text="Faqat shaxsiy (reply) bildirishnoma uchun. Admin xabari hammaga bo'lsa bo'sh qoldiring.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/frames/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kichik raqam avval chiqadi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='my_app.movie')),
            ],
            options={
                'verbose_name': 'Anime kadr',
                'verbose_name_plural': 'Anime kadrlar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text="So'ralgan summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Qarz so'rovi",
                'verbose_name_plural': "Qarz so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text="Kiritmoqchi bo'lgan summa (so'm)")),
                ('image', models.ImageField(upload_to='balance_topups/%Y/%m/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hisobni to'ldirish so'rovi",
                'verbose_name_plural': "Hisobni to'ldirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimeVoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_vote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimeRequestSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anime_request_suggestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobim tarixi',
                'verbose_name_plural': 'Hisobim tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_replies', to='my_app.animenews'),
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='my_app.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='ReelBestLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='my_app.reelbest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reelbest_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reel')},
            },
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='my_app.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notice')},
            },
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='my_app.animenews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Like',
                'verbose_name_plural': 'News Likes',
                'unique_together': {('user', 'news')},
            },
        ),
        migrations.CreateModel(
            name='JackpotCodeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='my_app.jackpotcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jackpot_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AnimeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='my_app.animevoterequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('request', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AnimeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('daily', 'Kunlik anime'), ('film', 'Anime film')], help_text="Qaysi bo'limga chiqishi kerak", max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kichik raqam avval chiqadi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(help_text="Nomi bo'yicha animani tanlang", on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='my_app.movie')),
            ],
            options={
                'verbose_name': "Kategoriya bo'limi (Kunlik/Film)",
                'verbose_name_plural': "Kategoriya bo'limlari (Kunlik/Film)",
                'ordering': ['order', '-created_at'],
                'unique_together': {('section', 'movie')},
            },
        ),
    ]
