# Generated by Django 4.2.11 on 2026-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_vipthankvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='premium_vip_box_on',
            field=models.BooleanField(default=False, help_text="Yoqilsa, chatda boshqalar sizning avataringizga bosganda oddiy profil o'rniga maxsus VIP box ochiladi"),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='vip_box_show_recent_anime',
            field=models.BooleanField(default=True, help_text="VIP box ichida oxirgi ko'rilgan animelarni ko'rsatish"),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='vip_box_show_vip_expire',
            field=models.BooleanField(default=True, help_text="VIP box ichida VIP obuna tugash sanasini ko'rsatish"),
        ),
    ]
