# Generated by Django 5.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_usersettings_premium_vip_box_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='vip_box_video',
            field=models.ForeignKey(
                blank=True,
                help_text='VIP foydalanuvchi tanlagan maxsus VIP box videosi',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='my_app.vipthankvideo'
            ),
        ),
    ]
